# Generated by Django 5.1.15 on 2026-03-27 18:28

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('service_list_title', models.CharField(blank=True, default='Service List Title', max_length=100)),
            ],
            options={
                'verbose_name': 'Service Page',
                'verbose_name_plural': 'Service Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ServiceListOrderable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('card_serial', models.IntegerField(blank=True, null=True)),
                ('card_title', models.CharField(blank=True, default='Card Title', max_length=100)),
                ('card_summary', wagtail.fields.StreamField([('content', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'li', 'ul', 'hr', 'h3'], 'template': 'blocks/richtext.html'})})),
                ('cta_text', models.CharField(blank=True, max_length=100)),
                ('cta_url', models.URLField(blank=True)),
                ('cta_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='service.servicepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
