# Generated by Django 5.1.15 on 2026-04-04 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
    ]
