# Generated by Django 5.1.15 on 2026-04-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_delete_servicecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='service_category',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
