# Generated by Django 5.1.15 on 2026-03-30 19:09

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Work Page',
                'verbose_name_plural': 'Work Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='WorkTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Work Tag',
                'verbose_name_plural': 'Work Tags',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('serial_number', models.IntegerField(blank=True, help_text='The order of the work item in the list', null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', wagtail.fields.StreamField([('content', 0)], blank=True, block_lookup={0: ('work.blocks.APIRichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'li', 'ul', 'hr', 'h3'], 'template': 'blocks/richtext.html'})})),
                ('project_url', models.URLField(blank=True, help_text='URL to the project, e.g. live demo')),
                ('repo_url', models.URLField(blank=True, help_text='URL to the code repository, e.g. GitHub')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_items', to='work.workindexpage')),
                ('work_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkItemTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('work_item', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_tag_items', to='work.workorderable')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='work.worktag')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
