# Generated by Django 5.1.15 on 2026-03-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herocounter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
