# Generated by Django 5.1.15 on 2026-03-29 15:36

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Resume Page',
                'verbose_name_plural': 'Resume Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ResumeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeOrderable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(blank=True, default='Resume Title', max_length=100)),
                ('sub_title', models.CharField(blank=True, default='Resume Sub Title', max_length=100)),
                ('description', wagtail.fields.StreamField([('content', 0)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'li', 'ul', 'hr', 'h3'], 'template': 'blocks/richtext.html'})})),
                ('language_tags', modelcluster.fields.ParentalManyToManyField(blank=True, to='resume.languagetag')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_items', to='resume.resumeindexpage')),
                ('resume_categories', modelcluster.fields.ParentalManyToManyField(blank=True, to='resume.resumecategory')),
                ('resume_tags', modelcluster.fields.ParentalManyToManyField(blank=True, to='resume.resumetag')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
