# Generated by Django 5.1.15 on 2026-03-29 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='languagetag',
            options={'verbose_name': 'Language Tag', 'verbose_name_plural': 'Language Tags'},
        ),
        migrations.AlterModelOptions(
            name='resumecategory',
            options={'verbose_name': 'Resume Category', 'verbose_name_plural': 'Resume Categories'},
        ),
        migrations.AlterModelOptions(
            name='resumetag',
            options={'verbose_name': 'Resume Tag', 'verbose_name_plural': 'Resume Tags'},
        ),
    ]
