# Generated by Django 5.1.15 on 2026-03-29 16:53

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_languagetag_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumeorderable',
            name='language_tags',
        ),
        migrations.RemoveField(
            model_name='resumeorderable',
            name='resume_categories',
        ),
        migrations.RemoveField(
            model_name='resumeorderable',
            name='resume_tags',
        ),
        migrations.CreateModel(
            name='ResumeItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='resume.resumecategory')),
                ('resume_item', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_items', to='resume.resumeorderable')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResumeItemLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='resume.languagetag')),
                ('resume_item', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_items', to='resume.resumeorderable')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResumeItemTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('resume_item', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_items', to='resume.resumeorderable')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='resume.resumetag')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
